POST http://localhost:5000/insertar_empleado
Content-Type: application/json

{
  "Puesto": "Cuidador",
  "valorDocumento": "123456789",
  "nombre": "Dilano Bermudez", 
  "fechaContratacion": "2021-10-10",
  "username": "Erick"
}


### Consultar empleados
GET http://localhost:5000/listar_empleados

### Consultar empleado por Documento
GET http://localhost:5000//empleados/filtro?search=Camila&username=Erick

### Obtener puestos
GET http://localhost:5000/puestos

### get empleado by id
GET http://localhost:5000//modificaremp/getEmpleado?search=6789012

### Modificar empleado
POST http://localhost:5000/modificaremp
Content-Type: application/json

{
  "Puesto": "Cuidador",
  "valorDocumentoAnterior": "987654",
  "valorDocumentoNuevo": "987654321",
  "nombreAnterior": "Andrea Vargas", 
  "nombreNuevo": "Andrea Vargas", 
  "saldoVacaiones": 0,
  "username": "Erick"
}