POST http://localhost:5000/insertar_empleado
Content-Type: application/json

{
  "nombre": "Dilana Bermudez", 
  "salario": 50000
}


### Consultar empleados

GET http://localhost:5000/listar_empleados

### Login
GET  http://localhost:5000/login
Content-Type: application/json

{
  "usuario": "Erick", 
  "contrasena": "1234"
}